<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://linkcare.es/LINKCARE"
                  xmlns="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:apachesoap="http://xml.apache.org/xml-soap"
                  xmlns:intf="http://linkcare.es/LINKCARE"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <wsdl:message name="service_brca_scoringRequest">
        <wsdl:part name="form_id" type="xsd:string"/>
        <wsdl:part name="scoring_task_id" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="service_brca_scoringResponse">
        <wsdl:part name="result" type="xsd:string"/>
        <wsdl:part name="ErrorMsg" type="xsd:string"/>
    </wsdl:message>

    <wsdl:portType name="LINKCARE">
        <wsdl:operation name="service_brca_scoring" parameterOrder="form_id scoring_task_id result ErrorMsg">
            <wsdl:input message="intf:service_brca_scoringRequest" name="service_brca_scoringRequest"/>
            <wsdl:output message="intf:service_brca_scoringResponse" name="service_brca_scoringResponse"/>
        </wsdl:operation>
    </wsdl:portType>


    <wsdl:binding name="LINKCARESoapBinding" type="intf:LINKCARE">
        <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="service_brca_scoring">
            <wsdlsoap:operation soapAction="LINKCARE#service_brca_scoring"/>
            <wsdl:input name="service_brca_scoringRequest">
                <wsdlsoap:body
                        encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                        namespace="http://linkcare.es/LINKCARE"
                        use="encoded"/>
            </wsdl:input>
            <wsdl:output name="service_brca_scoringResponse">
                <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                               namespace="http://linkcare.es/LINKCARE"
                               use="encoded"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="LINKCARE">
        <wsdl:port binding="intf:LINKCARESoapBinding" name="LINKCARE">
            <wsdlsoap:address location="https://demo-api.linkcare.es/services/workflow/BRCA/Server.php"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
